# Generated by Django 5.2.11 on 2026-03-05 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Listening date')),
                ('listen_type', models.CharField(choices=[('F', 'Full listen'), ('P', 'Partial listen'), ('R', 'Re-listen')], default='F', max_length=1)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.album')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
