# Generated by Django 5.2.11 on 2026-03-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='imagine_url',
            field=models.URLField(blank=True),
        ),
    ]
