# Generated by Django 5.2.11 on 2026-03-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_album_imagine_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='imagine_url',
            new_name='image_url',
        ),
    ]
